name: build

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs)

      - uses: actions/checkout@v4

      - name: check
        run: cargo check --all-features

      - name: build release
        run: cargo build --all-features --release

      - name: build benchmarks
        run: cargo test --all-features --benches --no-run
